#!/bin/bash
#
#SBATCH --job-name=mpi_bfly_128_l
#SBATCH --qos janus
#SBATCH --nodes 128
#SBATCH --ntasks-per-node 1
#SBATCH --time 00:3:00
#SBATCH --output results_128_l_512.out

module load slurm
module load gcc
module load openmpi/1.8.5

mpirun -np 128 ./bfly.out -l 512
	